// src/app/shared/icons/lucide-icons.ts
import { Lock, Mail, Building, Users, User, Search, ArrowLeft, CheckCircle, Monitor, Laptop, Ticket, LogOut, LayoutDashboard, Bell, Menu, Edit, Trash, Plus, Filter, Funnel, icons, Info, X, LogIn, AlertCircle, Clock, XCircle, Eye, MessageSquare, History, MessageCircle, UserCheck, Wrench, Box, HelpCircle} from 'lucide-angular';

export const LucideIconCollection = {
  Lock,
  Mail,
  Building,
  Users,
  User,
  Search,
  ArrowLeft,
  CheckCircle,
  Monitor,
  Laptop,
  Ticket,
  LogOut,
  LayoutDashboard,
  Bell,
  Menu,
  Edit,
  Trash,
  Plus,
  Funnel,
  icons,
  Info,
  X,
  LogIn,
  AlertCircle,
  Clock,
  XCircle,
  Eye,
  MessageSquare,
  History,
  MessageCircle,
  UserCheck,Wrench,
  Box,
  HelpCircle
};
